### ISSUE TITLE
Basic Example doesn't log

### ISSUE THREAD

**Issue by ivan-kleshnin** [gajus/slonik-interceptor-query-logging#1]
I'm trying the basic example (fixed a bit):

```diff
// test.js
import {
+  sql,
  createPool
} from 'slonik';
import {
  createQueryLoggingInterceptor
} from 'slonik-interceptor-query-logging';

const interceptors = [
  createQueryLoggingInterceptor()
];

- const pool = createPool('postgres://', {
+ const pool = createPool('postgres://postgres@localhost/mydb', {
  interceptors
});

- await connection.any(sql`
+ pool.any(sql`
  SELECT * FROM "post"
`)
```

```
$ babel-node test.js
```

And it doesn't log anything at all. 

Does this library require some external PostgreSQL configuration that aren't mentioned in README?  

---

I use default `homebrew` PG install on OSX and the latest versions of `slonik` and this lib.

**Comment by gajus** [comment]
You have to export `ROARR_LOG=true` environment variable.
