### ISSUE TITLE
Recommendation for passing in correlation ID from containing context

### ISSUE THREAD

**Issue by AndrewO** [gajus/slonik-interceptor-query-logging#3]
I have an Slonik web app that logs multiple log lines as JSON. I'd like to be able to correlate those lines together with a per-request correlation identifier. I'm trying to figure out the best way to add that to the `roarr` context, ideally using this middleware and not requiring me to pass that context along with my application queries.

So assuming I have a data access class like:

```js
class MyService {
  // Called by the framework on each request.
  initialize(context) {
     // context has pool (with slonik-interceptor-query-logging applied)
     // and correlationId, provided by the containing application.
     this.pool = context.pool;
     // Somehow send context.correlationId to pool's context and/or create a child log
     // so slonik-interceptor-query-logging gets it?
     ...
  }

  getStuffForUser(userId) {
    // Nothing about the correlation ID here.
    return this.pool.query(sql`SELECT * FROM stuff WHERE user_id = ${userId}`);
  }
}
```

(For full context, this is actually [an Apollo Data Source](https://www.apollographql.com/docs/apollo-server/data/data-sources/), hence the `initialize` method.)

Looking through the various pool and transaction context types, I don't have a good idea of where I can add new properties or what would be safe to replace. Any recommendations?

**Comment by gajus** [comment]
https://github.com/gajus/roarr#roarr-api-adopt
